dist: xenial
language: python
python:
- 3.6
env:
  global:
  - PYPI_API_TOKEN=notreallyatoken
# cache:
# - pip
# - apt
# install:
# - pip install pipenv
# - pipenv install --dev --deploy
# - pipenv graph
install:
- 'curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | POETRY_PREVIEW=1 python'
- source $HOME/.poetry/env
- which poetry
- poetry install -v
script:
- poetry run pytest -vv tests/
# - pipenv run pytest -vv --cov=gen3utils --cov-report xml ./tests
# after_script:
# - pipenv run python-codacy-coverage -r coverage.xml
before_deploy:
- poetry config pypi-token.pypi $PYPI_API_TOKEN
- poetry build -f sdist
deploy:
  provider: script
  script: poetry publish -vvv --dry-run
  user: uc-ctds
  skip_existing: true
  skip_cleanup: true
  on:
    all_branches: true # XXX need to remove
    repo: uc-cdis/gen3utils
    # tags: true
  password:
    secure: hN2GR0mCufwG6d+LaJ2EoOP2WH1DhaO7AgVN6RwEeetdlfhOv55dpfYFJkeZKyDKXj+gsTFB38h0JrnDEjoJE2Rp/1+pbVbotDETe3eO+mXiG/gtr+qt9Q0leQpy1SanQG7sBu/vA4RZ/D6yRgNXgmJhjaDkO9CjoyBlaOK5ykkWwL9VzjTO2cjW3waYHaBhLJG6JFRp3NwRnVRqYaWoGifrzDUbtsecW5wTnPY4HYJEz/K8J/bQch/OP+MYxm0gwgEwX9QxRAr1BbUuZmEIuav7LELQ8Y50tN2QO2TS9C3vKy68270JMrdl88XpwV60e3KwyTezK2c7SYQwDMYcpSR3kxEAPCT3pJ1A1+G1RpcLVRDzqMP3kRw/kTlK/G4DsiVhfY9IKL8xPoA1Xb/8YBmxdJvM/kTwzLxSUKfZIQxZ80ix9Am/6AQVp3beaagfl9Jtl8okmcHrS+y1CeFcJBzuBsIbnckY9VqPNg89hfo9zNQ9oOSKXcjxkSESzpmrJrMehcndtNKizlN7WESdpgs3MWJXXbp9c4gsVT2Dr3xyMj1S7Jat2ZY3l9x8LU4NvRPjS+JtxIOo+j8G0o5/rR3YXw5PDFppzav1hKiNInPziQ1C9w1S3j8qqyl8yS3b6a9/KoXg+bIT+a1s9D2cVyicA1RJuNqA3ix1SmESgH0= # pragma: allowlist secret
after_deploy:
- poetry run gen3git gen
- cat release_notes.txt
